version: '3'

services:
  # Step 1: Avvia un container per scaricare e buildare il progetto Spring Boot
  builder:
    image: maven:3.9.6-eclipse-temurin-11
    volumes:
      - ./Florence:/app
    command: >
      bash -c "
        rm -rf /app/*
        git clone https://github.com/DoM-D-DoM/Florence.git /app &&
        cd /app && chmod +x mvnw &&
        ./mvnw clean install
      "

  # Step 2: Avvia un secondo container con MariaDB
  database:
    image: mariadb
    networks:
      - mynetwork
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'

  # Step 3: Avvia un terzo container per l'applicazione Spring Boot
  app:
    image: maven:3.9.6-eclipse-temurin-11
    networks:
      - mynetwork
    volumes:
      - ./Florence:/app
    depends_on:
      - builder
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/Florence
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
    command: >
      bash -c "
        while [ ! -f /app/.build_completed ]; do sleep 1; done &&
        cd /app &&
        java -jar target/tuo-progetto.jar
      "

networks:
  mynetwork:
    driver: bridge
